github_token: ghp_abc123

# Shared Settings
# Team that contains all "internal" members
internal_team: "my-org/my-team"

# If empty, internal label will not be added
label_internal: "internal-pr"
# If empty, external label will not be added
label_external: "community-pr"
# Repos to check for labeling
label_check_repos:
  - "my-org/repo1"
  - "my-org/repo2"
# PRs opened by these users will not be labeled
label_skip_users:
  - "dependabot[bot]"
# Only PRs with a number higher than this value will be labeled
label_minimum_number: 0
